version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    restart: unless-stopped
